# Generated by Django 5.2.4 on 2025-07-11 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accession_number', models.CharField(blank=True, max_length=100, null=True)),
                ('organism', models.CharField(max_length=100)),
                ('function', models.TextField()),
                ('sequence_file', models.FileField(blank=True, null=True, upload_to='genes/sequences/')),
            ],
        ),
        migrations.CreateModel(
            name='PlantLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('callus', 'Callus'), ('shoot', 'Shoot'), ('rooted', 'Rooted'), ('acclimatized', 'Acclimatized'), ('lost', 'Lost'), ('confirmed', 'Confirmed')], max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plant_lines/')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Primer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sequence', models.TextField()),
                ('melting_temp', models.FloatField()),
                ('product_size_bp', models.IntegerField()),
                ('supplier', models.CharField(max_length=100)),
                ('lot_number', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(help_text='e.g., binary, plasmid', max_length=100)),
                ('antibiotic_resistance', models.CharField(max_length=100)),
                ('map_file', models.FileField(blank=True, null=True, upload_to='vectors/maps/')),
            ],
        ),
        migrations.CreateModel(
            name='Construct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cloning_method', models.CharField(help_text='e.g., Gibson, TA, Gateway', max_length=100)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labcore.gene')),
                ('vector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labcore.vector')),
            ],
        ),
        migrations.CreateModel(
            name='PCRRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enzyme', models.CharField(max_length=100)),
                ('annealing_temp', models.FloatField()),
                ('cycles', models.IntegerField()),
                ('buffer', models.CharField(max_length=100)),
                ('success', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('gel_image', models.ImageField(blank=True, null=True, upload_to='pcr/gels/')),
                ('date', models.DateField(auto_now_add=True)),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labcore.construct')),
                ('forward_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fwd_pcrs', to='labcore.primer')),
                ('reverse_primer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev_pcrs', to='labcore.primer')),
            ],
        ),
        migrations.CreateModel(
            name='PCRConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('inconclusive', 'Inconclusive')], max_length=100)),
                ('gel_image', models.ImageField(blank=True, null=True, upload_to='confirmations/gels/')),
                ('notes', models.TextField(blank=True)),
                ('confirmed_on', models.DateField(auto_now_add=True)),
                ('plant_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labcore.plantline')),
                ('primers_used', models.ManyToManyField(to='labcore.primer')),
            ],
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='protocols/')),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('protocol_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='labcore.protocol')),
            ],
        ),
        migrations.CreateModel(
            name='TransformationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(help_text='e.g., Agrobacterium, Electroporation', max_length=100)),
                ('competent_strain', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('efficiency_percent', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('construct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labcore.construct')),
            ],
        ),
        migrations.AddField(
            model_name='plantline',
            name='transformation_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labcore.transformationevent'),
        ),
    ]
